### PR TITLE
refactor: A better size calculation for SecondWindow

### PR DESCRIPTION
**Pull request by l619534951**
We don't need "FirstMeasure" and "SecondMeasure"  now, and the menu is always displayed consistently.

### CODE REVIEW

**Comment by HavenDV** [comment]
image

**Comment by HavenDV** [comment]
Unfortunately, the problem of the first calculation of the width is not solved. Tested on H.NotifyIcon.Apps.WinUI project

**Comment by l619534951** [comment]
do not use "XamlUICommand", binding command from ViewModel directly.

**Comment by l619534951** [comment]
This problem also appears when use "ToggleMenuFlyoutItem", shall we open a new issue ?

**Pull request merged**
